### ISSUE TITLE
What is the '/home/ubuntu/Data_ABC/ip_simulated_1million.txt'?

### ISSUE THREAD

**Issue by cui-xiaoang96** [vishaldas/CNN_based_impedance_inversion#1]
Helleo, I have to say that your opened codes are vary useful for me. Thank you for your great share.

I have a dimple question that what is the '/home/ubuntu/Data_ABC/ip_simulated_1million.txt' found in your the CNN_impedance_inversion-ABC.ipynb of first folder.
![Inked3CYRK50Y9DNNY2~L7Y_L3 W_LI](https://user-images.githubusercontent.com/41711907/68724464-89c98300-05f6-11ea-9222-ca14e83dc28e.jpg)
Where could I find the file or what methods could I creat it?

Any help would be much appreciated - thanks!

**Comment by vishaldas** [comment]
This is the data for ABC computation. It is too big to include in the github repository. This has been mentioned in the Readme file of the repository

![image](https://user-images.githubusercontent.com/17754914/68724721-20ebf780-0571-11ea-955a-8a4096fe7b8f.png)

Thanks,
Vishal

**Comment by cui-xiaoang96** [comment]
Dear Dr. das:


I'm sorry to write the e-mail to you. Maybe it will bother you.


I  have read your great papers named "Convolutional neural network for  seismic impedance inversion" and "Convolutional Neural Network for  Seismic Impedance Inversion". I think they are very interesting and  heuristic to me. Especially, you had opened your codes and data. it is  so cool.


And I have a questions for your opened repositoies at https://github.com/vishaldas/CNN_based_impedance_inversion. I want to get the file named "/home/ubuntu/Data_ABC/ip_simulated_1million.txt" in the first folder. Could you send it to me. Or What should I do to get it. 



Looking forward to your reply. 



Bets wish for you,
Rongang Cui



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月13日(星期三) 上午9:23
收件人:&nbsp;"vishaldas/CNN_based_impedance_inversion"<CNN_based_impedance_inversion@noreply.github.com&gt;;
抄送:&nbsp;"1612678828"<1612678828@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vishaldas/CNN_based_impedance_inversion] What is the '/home/ubuntu/Data_ABC/ip_simulated_1million.txt'? (#1)




This is the data for ABC computation. It is too big to include in the github repository. This has been mentioned in the Readme file of the repository
 

 
Thanks,
 Vishal

**Comment by vishaldas** [comment]
Hi Rongang,

Please find below link to the data file.

https://office365stanford-my.sharepoint.com/:t:/g/personal/vdas2_stanford_edu/EZ6OrrjXs9FFpN9O5R-TCU0B_2Id_sN-lqtiUA9XfWB_tg?e=Ag7Jn8

Hope this helps solve your issue.

Thanks,
Vishal

**Comment by cui-xiaoang96** [comment]
Dear Vishal,


Thanks for your generous help very very very much.


It has worked with the file named 'ip_simulated_1million.txt'. 



Thanks for sharing.



Thanks you,
Rongang Cui.



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"notifications"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 凌晨2:41
收件人:&nbsp;"vishaldas/CNN_based_impedance_inversion"<CNN_based_impedance_inversion@noreply.github.com&gt;;
抄送:&nbsp;"1612678828"<1612678828@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [vishaldas/CNN_based_impedance_inversion] What is the '/home/ubuntu/Data_ABC/ip_simulated_1million.txt'? (#1)



Hi Rongang, 
 
 Please find below link to the data file. 
 
 https://office365stanford-my.sharepoint.com/:t:/g/personal/vdas2_stanford_edu/EZ6OrrjXs9FFpN9O5R-TCU0B_2Id_sN-lqtiUA9XfWB_tg?e=Ag7Jn8 
 
 Hope this helps solve your issue. 
 
 Thanks, 
 Vishal

**Comment by soutik451** [comment]
Dear Sir,

I hope this message finds you well.

I wanted to inform you that the link you provided for accessing the dataset ([link](https://office365stanford-my.sharepoint.com/:t:/g/personal/vdas2_stanford_edu/EZ6OrrjXs9FFpN9O5R-TCU0B_2Id_sN-lqtiUA9XfWB_tg?e=Ag7Jn8)) has expired. Could you kindly assist by sharing an updated link or alternative access to the dataset?

Thank you very much for your help.

Best regards,
Soutik Bhakta
